-- Flyway migration: cria tabela subscribers de forma compatível com Postgres e H2
CREATE TABLE IF NOT EXISTS subscribers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(320) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    provider VARCHAR(50) NOT NULL,

    first_name VARCHAR(150),
    last_name VARCHAR(150),
    phone VARCHAR(100),
    document VARCHAR(100),
    zipcode VARCHAR(50),
    city VARCHAR(150),
    state VARCHAR(150),
    country VARCHAR(150),

    product_id VARCHAR(100),
    product_name VARCHAR(255),
    transaction_id VARCHAR(200),

    price NUMERIC(19,4),
    currency VARCHAR(10),
    purchase_date TIMESTAMP WITHOUT TIME ZONE
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_subscribers_email ON subscribers(email);
